apiVersion: v1
kind: Pod
metadata:
  name: aspnetcore
  labels:
    app: aspnetcore
spec:
  containers:
  - image: aksadvancedacr.azurecr.io/aspnet:latest
    name: aspnetcore
    ports:
    - containerPort: 80
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: aspnetcore
spec:
  selector:
    app: aspnetcore
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aspnetcore
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: aspnetcore
            port:
              number: 80
        pathType: Exact